# Generated by Django 3.2 on 2023-06-18 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ENtitle', models.CharField(blank=True, max_length=200)),
                ('ENcontent', models.TextField()),
                ('ENauthor', models.CharField(default='ChenYu', max_length=200)),
                ('ENsummary', models.CharField(default='The weak is the recognition of love, just as giving up is the antidote of noise', max_length=200)),
                ('CHtitle', models.CharField(blank=True, max_length=200)),
                ('CHcontent', models.TextField()),
                ('CHauthor', models.CharField(default='尘语', max_length=200)),
                ('CHsummary', models.CharField(default='惟柔弱是爱愿的识别，正如放弃是喧嚣的解剂', max_length=200)),
                ('cover', models.ImageField(default='static/no-img.jpg', upload_to='medias/covers/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.category', to_field='name')),
            ],
        ),
    ]
