# Generated by Django 4.1.7 on 2023-06-16 04:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="content",
            new_name="CHcontent",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="title",
        ),
        migrations.AddField(
            model_name="blog",
            name="CHauthor",
            field=models.CharField(default="尘语", max_length=200),
        ),
        migrations.AddField(
            model_name="blog",
            name="CHsummary",
            field=models.CharField(default="惟柔弱是爱愿的识别，正如放弃是喧嚣的解剂", max_length=200),
        ),
        migrations.AddField(
            model_name="blog",
            name="CHtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="blog",
            name="ENauthor",
            field=models.CharField(default="ChenYu", max_length=200),
        ),
        migrations.AddField(
            model_name="blog",
            name="ENcontent",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blog",
            name="ENsummary",
            field=models.CharField(
                default="The weak is the recognition of love, just as giving up is the antidote of noise",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="ENtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="blog",
            name="cover",
            field=models.ImageField(
                default="static/no-img.jpg", upload_to="medias/covers/"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
