# Generated by Django 3.2 on 2023-06-23 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_auto_20230623_0206"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="category",
            field=models.ForeignKey(
                default="Life",
                on_delete=django.db.models.deletion.CASCADE,
                to="blogs.category",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="ENsummary",
            field=models.CharField(
                default="Lorem Ipsum is simply dummy text of the printing and typesetting industry.",
                max_length=200,
            ),
        ),
    ]
