# Generated by Django 3.2 on 2023-06-23 09:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0006_remove_blog_belong_to_collection"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together={("name", "category")},
        ),
    ]
