# Generated by Django 3.2 on 2023-06-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0007_alter_collection_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name="collection",
            unique_together=set(),
        ),
    ]
