# Generated by Django 4.1.7 on 2023-07-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
