# Generated by Django 4.1.7 on 2023-07-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_users_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="users",
            old_name="user",
            new_name="username",
        ),
        migrations.AlterField(
            model_name="users",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
