name: Deploy to DigitalOcean

on:
  push:
    branches:
      - api

jobs:
  build_and_push:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Frontend Docker images
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:frontend"
          push: true
          tags: moringspeaker/frontend:latest
          file: Dockerfile

      - name: Build and push Backend Docker images
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:backend"
          push: true
          tags: moringspeaker/backend:latest
          file: Dockerfile


  deploy:
    needs: build_and_push
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Droplet
        run: |
          ssh -i ${{ secrets.DROPLET_SSH_KEY }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} <<'ENDSSH'
          docker pull moringspeaker/frontend:latest
          docker pull moringspeaker/backend:latest
          ls -a
#          docker run -d --name my_frontend --env-file ./.env -p 80:80 moringspeaker/frontend:latest
#          docker run -d --name my_backend --env-file ./.env -p 8000:8000 moringspeaker/backend:latest
#          # more commands
#          ENDSSH

