name: Deploy to DigitalOcean

on:
  push:
    branches:
      - api

jobs:

  deploy:
    needs: build_and_push
    runs-on: ubuntu-22.04

    steps:
      - name: Deploy to Droplet
        uses: D3rHase/ssh-command-action@v0.22
        with:
          host: ${{ secrets.SSH_HOST }} # Remote server address / ip - required
          port: ${{ secrets.SSH_PORT }} # Remote server port -  Default: 22 - optional
          user: ${{ secrets.SSH_USER }} # Remote server user - required
          private_key: ${{ secrets.DROPLET_SSH_KEY }} # Private ssh key registered on the remote server - required

          command: echo 'hello world' && ls -a && pwd
#          docker run -d --name my_frontend --env-file ./.env -p 80:80 moringspeaker/frontend:latest
#          docker run -d --name my_backend --env-file ./.env -p 8000:8000 moringspeaker/backend:latest
#          # more commands
#          ENDSSH

